/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC721G__factory } from "./IERC721G__factory";
export { IGaiaNFTBridge__factory } from "./IGaiaNFTBridge__factory";
